# ##### writing a file
# ### file handling can be error-prone so we use try statement
# ### to handle exceptions  

# ##### open(), write(), close() #####
file = open('02_file1_write_hello_chen.txt', 'w')   # 'w': write mode
try:
    file.write('file generated by 02_file1_write_hello_chen.py')
finally:
    file.close()
